spring.application.name=ht_vlxd

spring.datasource.url=jdbc:mysql://localhost:3306/vlxd_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Admin@123
spring.jpa.hibernate.ddl-auto=update

spring.thymeleaf.cache=false